BlogCMS/Controllers/BlogsController.cs
using BlogCMS.Models;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace BlogCMS.Controllers
{
    [Authorize]
    public class BlogsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        private ApplicationUserManager _userManager;

        public BlogsController()
        {
        }

        public BlogsController(ApplicationUserManager userManager)
        {
            UserManager = userManager;
        }        

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        // GET: Blogs
        public ActionResult Index(int? index)
        {
            int _startIndex = 0;
            int pageCount = 5;

            if (index != null)
            {
                if (index > 0)
                {
                    index = index - 1;
                }
                _startIndex = (int)index * pageCount;
            }

            int _endIndex = _startIndex + pageCount;

            
            int articleCount = db.Posts.Count();
            //classify = (input > 0) ? "positive" : "negative";
            ViewBag.Pages = (articleCount % pageCount == 0) ? articleCount / pageCount : (articleCount / pageCount) + 1;
            List<Post> list = db.Posts.OrderBy(a => a.Id).Skip(_startIndex).Take(_endIndex - _startIndex).ToList();

            int charCount = 100;
            for (int i = 0; i < list.Count; i++)
            {
                if (list[i].Description?.Length > charCount)
                {
                    string shortDesc = list[i].Description.Substring(0, charCount) + "...";
                    list[i].Description = shortDesc;
                }

            }
            return View(list);
        }

        // GET: Blogs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        // GET: Blogs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Blogs/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Post post)
        {
            if (ModelState.IsValid)
            {
                var user = await UserManager.FindByNameAsync(User.Identity.Name);
                post.PublisherId = user.Id;
                post.Published = DateTime.Now;

                db.Posts.Add(post);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(post);
        }

        // GET: Blogs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        // POST: Blogs/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(Post post)
        {
            if (ModelState.IsValid)
            {
                var user = await UserManager.FindByNameAsync(User.Identity.Name);
                post.PublisherId = user.Id;
                post.Published = DateTime.Now;

                db.Posts.Add(post);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(post);
        }

        // GET: Blogs/Delete/5
        public ActionResult Delete(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        // POST: Blogs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            try
            {
                Post post = db.Posts.Find(id);
                db.Posts.Remove(post);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

BlogCMS/Views/Blogs/Create.cshtml
@model BlogCMS.Models.Post
@{
    ViewBag.Title = "Create";
}

<div class="container" style="margin-top:50px;">
    <div class="row">
        <!-- Blog Sidebar Widgets Column -->
        <div class="col-sm-3">
            <!-- Blog Categories Well -->
            <div class="well">
                <h4>Dashboard</h4>
                <div class="row">
                    <div class="col-lg-12">
                        <ul class="list-unstyled"></ul>
                        @Html.Partial("_DashboardPartial", null)
                    </div>
                    <!-- /.col-lg-6 -->
                </div>
                <!-- /.row -->
            </div>
        </div>
        <div class="col-sm-9">
            <section class="well">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        <h4>Post</h4>
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2 text-right" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">                               
                                @Html.TextAreaFor(model => model.Description, new { @id="summernotetext", @class = "form-control", Rows = 10 })
                                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.isPublished, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.CheckBoxFor(model => model.isPublished, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.isPublished, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Create" class="btn btn-default" />
                            </div>
                        </div>
                    </div>
                }
            </section>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $(document).ready(function () {
            $('#summernotetext').summernote({
                height: 100,                 // set editor height
                minHeight: null,             // set minimum height of editor
                maxHeight: null,             // set maximum height of editor
                focus: true,
                themes: 'sandstone'
            });
        });
    </script>    
}

BlogCMS/Views/Blogs/Details.cshtml
@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

BlogCMS/Views/Blogs/Edit.cshtml
@model BlogCMS.Models.Post
@{
    ViewBag.Title = "Edit";
}

<div class="container" style="margin-top:50px;">
    <div class="row">
        <!-- Blog Sidebar Widgets Column -->
        <div class="col-sm-3">
            <!-- Blog Categories Well -->
            <div class="well">
                <h4>Dashboard</h4>
                <div class="row">
                    <div class="col-lg-12">
                        <ul class="list-unstyled"></ul>
                        @Html.Partial("_DashboardPartial", null)
                    </div>
                    <!-- /.col-lg-6 -->
                </div>
                <!-- /.row -->
            </div>
        </div>
        <div class="col-sm-9">
            <section class="well">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()
                    @Html.HiddenFor(model => model.Id)

                    <div class="form-horizontal">
                        <h4>Post</h4>
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.TextAreaFor(model => model.Description, new { @class = "form-control", Rows = 10 })
                                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.isPublished, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.CheckBoxFor(model => model.isPublished, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.isPublished, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Create" class="btn btn-default" />
                            </div>
                        </div>
                    </div>
                }
            </section>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BlogCMS/Views/Blogs/Index.cshtml
@model IEnumerable<BlogCMS.Models.Post>
@{
    ViewBag.Title = "Index";
}

<div class="container" style="margin-top:50px;">
    <div class="row">
        <!-- Blog Sidebar Widgets Column -->
        <div class="col-sm-3">
            <!-- Blog Categories Well -->
            <div class="well">
                <h4>Blogs Settings</h4>
                <div class="row">
                    <div class="col-lg-12">
                        <ul class="list-unstyled"></ul>
                        @Html.Partial("_DashboardPartial", null)
                    </div>
                    <!-- /.col-lg-6 -->
                </div>
                <!-- /.row -->
            </div>
        </div>
        <div class="col-sm-9">
            <section class="well">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>Post ID</th>
                            <th>Title</th>
                            <th>Registration date</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <th scope="row">@item.Id</th>
                                <td>@Html.ActionLink(@Html.DisplayFor(modelItem => item.Title).ToString(), "Edit", new { id = item.Id })</td>
                                <td>@item.Published</td>
                            </tr>
                        }
                    </tbody>
                </table>

                <nav aria-label="Page navigation">
                    <ul class="pagination">
                        <li>
                            <a href="?index=1" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>

                        </li>

                        @for (int i = 1; i <= @ViewBag.Pages; i++)
                        {
                            <li>
                                @Html.ActionLink(i.ToString(), "Index", new { index = i })
                            </li>
                        }


                        <li>
                            <a href="?index=@(Html.Raw(ViewBag.Pages))" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    </ul>
                </nav>
            </section>
        </div>
    </div>
</div>

BlogCMS/Views/Blogs/_DashboardPartial.cshtml
<ul class="list-group pmd-z-depth pmd-list pmd-card-list pmd-list-icon">
    <li class="list-group-item">
        <i class="material-icons media-left pmd-sm">Create</i>
        <span class="media-body">@Html.ActionLink("Blog", "Create", "Blogs")</span>
    </li>
    <li class="list-group-item">
        <i class="material-icons media-left pmd-sm">View</i>
        <span class="media-body">@Html.ActionLink("All Posts", "Index", "Blogs")</span>
    </li>
</ul>